# Generated by Django 4.2.9 on 2026-05-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_log', models.TextField(blank=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('data_type', models.CharField(choices=[('meltwater', 'Meltwater/X'), ('civicsignal', 'Civicsignal/Media'), ('tiktok', 'TikTok'), ('openmeasure', 'OpenMeasure/Telegram'), ('custom', 'Custom Format')], default='custom', max_length=50)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LexiconTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('target_entity', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('amharic', 'Amharic'), ('english', 'English'), ('oromo', 'Oromo'), ('tigrinya', 'Tigrinya')], max_length=20)),
                ('is_election_related', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(db_index=True, unique=True)),
                ('theme', models.CharField(max_length=255)),
                ('llm_summary', models.TextField()),
                ('total_reach', models.IntegerField(default=0)),
                ('virality_tier', models.CharField(choices=[('Tier 1: Limited', 'Tier 1: Limited'), ('Tier 2: Moderate', 'Tier 2: Moderate'), ('Tier 3: High Spread', 'Tier 3: High Spread'), ('Tier 4: Viral Emergency', 'Tier 4: Viral Emergency')], max_length=50)),
                ('first_detected', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_election_related', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-total_reach'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_id', models.CharField(db_index=True, max_length=255)),
                ('object_id', models.TextField()),
                ('original_text', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('timestamp_share', models.DateTimeField(db_index=True)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('is_original_post', models.BooleanField(default=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster', models.IntegerField(db_index=True, default=-1)),
                ('is_election_related', models.BooleanField(default=False)),
                ('election_keywords_matched', models.JSONField(blank=True, default=list)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('play_count', models.BigIntegerField(blank=True, null=True)),
                ('digg_count', models.BigIntegerField(blank=True, null=True)),
                ('comment_count', models.BigIntegerField(blank=True, null=True)),
                ('share_count', models.BigIntegerField(blank=True, null=True)),
                ('text_language', models.CharField(blank=True, max_length=10)),
                ('lexicon_matches', models.JSONField(blank=True, default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.datasource')),
            ],
            options={
                'ordering': ['-timestamp_share'],
                'indexes': [models.Index(fields=['timestamp_share'], name='dashboard_p_timesta_897858_idx'), models.Index(fields=['platform', 'timestamp_share'], name='dashboard_p_platfor_cfffdc_idx'), models.Index(fields=['cluster', 'timestamp_share'], name='dashboard_p_cluster_860b18_idx'), models.Index(fields=['is_election_related', 'timestamp_share'], name='dashboard_p_is_elec_ee8597_idx'), models.Index(fields=['risk_level', 'timestamp_share'], name='dashboard_p_risk_le_44dd1c_idx')],
            },
        ),
    ]
