# Generated by Django 4.2.9 on 2026-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('ethnic_group', models.CharField(blank=True, max_length=100)),
                ('x_link', models.URLField(blank=True, null=True)),
                ('x_verified', models.BooleanField(default=False)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('facebook_verified', models.BooleanField(default=False)),
                ('confidence_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('uncertain', 'Uncertain')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
