# Generated by Django 4.2.9 on 2026-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pep'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_analyst', models.CharField(blank=True, default='Internal Analyst', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('report_type', models.CharField(default='Investigative', max_length=50)),
                ('sample_urls', models.JSONField(blank=True, default=list, help_text='Sample posts/URLs found in the report')),
                ('extracted_text', models.TextField(blank=True, help_text='Raw extracted text from document')),
                ('summary', models.TextField(blank=True, help_text='Executive summary (manual entry)')),
                ('key_findings', models.JSONField(blank=True, default=list, help_text='List of key findings')),
                ('mentioned_entities', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('weaponised_narratives', models.JSONField(blank=True, default=list)),
                ('actor_spotlight', models.JSONField(blank=True, default=list)),
                ('ttp_infrastructure', models.JSONField(blank=True, default=list)),
                ('is_processed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Monitoring Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Brandwatch Weekly Export'", max_length=100, unique=True)),
                ('file_type', models.CharField(choices=[('csv_posts', 'Election Posts CSV'), ('csv_peps', 'PEPs/Candidates CSV'), ('pdf_report', 'Monthly Insight Report (PDF)'), ('json_narratives', 'Narratives/Clusters JSON')], max_length=50)),
                ('url', models.URLField(help_text='Raw/public URL to the file')),
                ('is_active', models.BooleanField(default=True)),
                ('sync_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pep',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='processedpost',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processedpost',
            name='ingested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedpost',
            name='content_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processedpost',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ElectionOfficeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('source_sheet', models.CharField(default='', max_length=100)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('column_order', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['source_file', 'source_sheet', 'row_index'],
                'unique_together': {('source_file', 'source_sheet', 'row_index')},
            },
        ),
    ]
