# Generated by Django 4.2.9 on 2026-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_monitoringreport_syncsource_datasource_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringreport',
            name='actor_spotlight',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='ttp_infrastructure',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='weaponised_narratives',
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='actor_spotlight_full',
            field=models.TextField(blank=True, help_text='Full text of actor spotlight section'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='key_findings_full',
            field=models.TextField(blank=True, help_text='Full text of key findings section'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='ttp_infrastructure_full',
            field=models.TextField(blank=True, help_text='Full text of TTP section'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='weaponised_narratives_full',
            field=models.TextField(blank=True, help_text='Full text of weaponised narratives section'),
        ),
    ]
