# Generated by Django 4.2.9 on 2026-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_monitoringreport_actor_spotlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreport',
            name='actor_spotlight',
            field=models.TextField(blank=True, help_text='Concise LLM-generated bullet summaries'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='ttp_infrastructure',
            field=models.TextField(blank=True, help_text='Concise LLM-generated bullet summaries'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='weaponised_narratives',
            field=models.TextField(blank=True, help_text='Concise LLM-generated bullet summaries'),
        ),
    ]
