# Generated by Django 4.2.9 on 2026-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_monitoringreport_actor_spotlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreport',
            name='full_report_url',
            field=models.URLField(blank=True, help_text='Link to full report (Google Drive, etc.)', null=True),
        ),
    ]
