# Generated by Django 4.2.9 on 2026-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_monitoringreport_full_report_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringreport',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='monitoringreport',
            name='sample_urls',
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Thumbnail for report cards', null=True, upload_to='report_covers/'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='report_category',
            field=models.CharField(choices=[('baseline', 'Baseline Report'), ('situational', 'Situational/TikTok Report'), ('biweekly', 'Bi-weekly/UN Monthly Report')], default='baseline', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='PDF/DOCX for direct download', null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='report_includes',
            field=models.JSONField(blank=True, default=list, help_text="Up to 5 bullet points: ['Analysis of...', 'Mapping of...']"),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short tagline under main title', max_length=300),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='actor_spotlight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='actor_spotlight_full',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='full_report_url',
            field=models.URLField(blank=True, help_text='Fallback external link', null=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='key_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='key_findings_full',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='summary',
            field=models.TextField(blank=True, help_text='Executive summary'),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='ttp_infrastructure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='ttp_infrastructure_full',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='weaponised_narratives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='weaponised_narratives_full',
            field=models.TextField(blank=True),
        ),
    ]
