# Generated by Django 4.2.9 on 2026-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_monitoringreport_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringreport',
            name='report_category',
            field=models.CharField(choices=[('baseline', 'Baseline Report'), ('situational', 'Situational Report'), ('tiktok', 'TikTok Analysis Report')], default='baseline', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='report_includes',
            field=models.JSONField(blank=True, default=list, help_text='Up to 5 bullet points'),
        ),
    ]
