# Generated by Django 6.0.7 on 2026-07-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lexiconterm',
            name='idx_category_severity',
        ),
        migrations.RemoveIndex(
            model_name='processedpost',
            name='idx_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='processedpost',
            name='idx_election_related',
        ),
    ]
