# Generated by Django 6.0.7 on 2026-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_lexiconterm_idx_category_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexiconterm',
            name='justification',
            field=models.TextField(blank=True, help_text='Why is this a trigger term?', null=True),
        ),
    ]
